version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.29
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  otel-collector:
    build:
      context: .
      dockerfile: Dockerfile-collector
    ports:
      - "4317:4317"        # OTLP gRPC receiver
      - "4318:4318"        # OTLP HTTP receiver
    depends_on:
      - jaeger
