services:
  jaeger:
    image: jaegertracing/all-in-one:1.29
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  otel-collector:
    image: otel/opentelemetry-collector:0.41.0
    command: ["--config=/etc/collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./collector-config.yaml:/etc/collector-config.yaml
    ports:
      - "4317:4317"        # OTLP gRPC receiver
      - "4318:4318"        # OTLP HTTP receiver
    depends_on:
      - jaeger
